### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by devxsss** [strongrex2001/discrete-math-helper#1]
Hello I got an error when compile,
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import lparser
  File "/home/Documents/discrete-math-helper-master/lparser.py", line 62
    return [v1[1], *var_list()]
                   ^
SyntaxError: invalid syntax

how to fix this?
Thankyou!

**Comment by strongrex2001** [comment]
Seems that you are using an unsupported version of python. I think >=3.5.3 will work for it.
Well, this is only a toy library by now. If you want better capabilities you may try the Microsoft Z3 Prover.
